[workspace]
members = [
    "qs-core",
    "qs-cli",
    "qs-roundezvous"
]

resolver = "2"

[workspace.dependencies]
quinn = { version = "0.11.4", features = ["runtime-tokio"] }
rustls = { version = "0.23.12", default-features = false, features = ["ring"] }
rcgen = "0.13.1"
bincode = "=2.0.0-rc.3"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.63"
pretty_assertions = "1.4.0"
rand = "0.8.5"
clap = { version = "4.5.16", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"
