[package]
name = "qs-cli"
version = "0.2.1"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
quinn = { workspace = true }
qs-core = { path = "../qs-core" }
async-compression = { version = "0.4.12", features = ["tokio", "gzip"] }
clap = { version = "4.5.16", features = ["derive"] }
indicatif = "0.17.8"
dialoguer = "0.11.0"

[[bin]]
path = "src/main.rs"
name = "qs"