name: Typos
on: [pull_request]

jobs:
  run:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v3

      - name: Check spelling
        uses: crate-ci/typos@master
